name: "Test - action"

on: 
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
      - next
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.3
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: make build

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.3
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Lint
      run: make lint
    - name: Unit Tests
      run: make test-unit
      env:
        CI: true

  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.3
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: e2e Tests
      run: make test-e2e
      env:
        CI: true

